name: Mirror to GitLab

on: [push]

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Mirror Repository to GitLab
      run: |
        git remote add gitlab http://gitlab.postex.ir/b.aghilinasab/ci.git
        git push --mirror gitlab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
